package com.wimbli.WorldBorder.cmd

import com.wimbli.WorldBorder.Config
import com.wimbli.WorldBorder.msg
import org.bukkit.command.CommandSender
import org.bukkit.entity.Player

class CmdFillautosave : WBCmd() {
    init {
        name = "fillautosave"
        permission = "fillautosave"
        minParams = 1
        maxParams = 1

        addCmdExample(nameEmphasized() + "<seconds> - world save interval for Fill.")
        helpText = "Default value: 30 seconds."
    }

    override fun cmdStatus(sender: CommandSender) {
        val seconds = Config.fillAutosaveFrequency
        if (seconds == 0) {
            sender.msg(C_HEAD + "World autosave frequency during Fill process is set to 0, disabling it.")
            sender.msg(
                C_HEAD + "Note that much progress can be lost this way if there is a bug or crash in " +
                    "the world generation process from Bukkit or any world generation plugin you use.",
            )
        } else {
            sender.msg(C_HEAD + "World autosave frequency during Fill process is set to $seconds seconds (rounded to a multiple of 5).")
            sender.msg(
                C_HEAD + "New chunks generated by the Fill process will be forcibly saved to disk " +
                    "this often to prevent loss of progress due to bugs or crashes in the world generation process.",
            )
        }
    }

    override fun execute(sender: CommandSender, player: Player?, params: MutableList<String>, worldName: String?) {
        val seconds: Int
        try {
            seconds = params[0].toInt()
            if (seconds < 0) {
                throw NumberFormatException()
            }
        } catch (ex: NumberFormatException) {
            sendErrorAndHelp(sender, "The world autosave frequency must be an integer of 0 or higher. Setting to 0 will disable autosaving of the world during the Fill process.")
            return
        }

        Config.setFillAutosaveFrequency(seconds)

        if (player != null) {
            cmdStatus(sender)
        }
    }
}
